Add browser config
luc-tielen/telescope_hoogle pull request #1
Opened 2021-03-27 22:34 UTC by ndzik

First of, thanks for your talk about `souffle-haskell`, I highly enjoyed that one ;D

I was in need of configuring the browser command, which is used to open the urls, so I thought why not make a PR for this (:

I did not find a good way to circumvent creating a "global" Hoogle module,  which is returned in `hoogle/live_hoogle_search.lua` and now exposes `H.setup()` and `H.live_hoogle_search()`. The way I understood telescope is, that defaults should be set in the `telescope.setup({ extensions = { -- extension_name = { extension_opts... } })` hook by the user.

You can also read the first commit message.

If you want me to change something, do not hesitate. Maybe you even have an idea which allows this to be less stateful. (I was hoping for telescope to pass standard `opts` to an extension's exposed functions but this does not seem to be the case :/ )

Kind regards, ndzik.

2021-03-29 06:45 UTC, luc-tielen commented
Thanks for the contribution! I have a busy week ahead of me, so I won't be able to review/merge it straight away. But I will look into it later.. :)

2021-03-29 07:38 UTC, ndzik commented
Take all the time you need :muscle:

2021-04-07 10:41 UTC, luc-tielen requested changes
So I did some looking around at other telescope extensions. Looks like you can directly call each individual function and pass in options that way. For example, see bottom of https://github.com/bi0ha2ard/telescope-ros.nvim.

For this extension, it would be: 
```lua
require('telescope').extensions.hoogle.hoogle { 
  -- your options here
}
```

With some vimrc magic you can call this from your keybindings. 😃  I think we should put this in a README (something similar like the link mentioned earlier, or the usage section from this plugin: https://github.com/nvim-telescope/telescope-vimspector.nvim)

(Which means you would only need the change to dynamically set browser config, and can get rid of global state again.)

2021-04-07 10:41 UTC, luc-tielen commented on README.md
> +5. Add the following Lua snippet to your nvim config:
Thanks for helping me count :sweat_smile: :joy:

2021-04-14 14:27 UTC, ndzik commented
Sorry, I was occupied last week. I will get this resolved this evening (:

Thanks your taking a look :muscle:

2021-04-14 17:32 UTC, ndzik commented
I am right now investigating what might cause telescope_hoogle not working correctly with the current `telescope.nvim:master`.

The merge of #709 really did break something. Other plugins also have this issue as can be seen here:

https://github.com/nvim-telescope/telescope.nvim/issues/748

If I am able to find a solution, I will include it in this PR if that is okay with you (:

2021-04-14 18:35 UTC, ndzik commented
I ran out of time for today. I don't know what exactly causes the issue. Explicitly setting the `sorter` in `live_hoogle_search` for `pickers.new(...)` fixes the error message shown in the referenced issue from `telescope.nvim`.

But after doing that no results are being printed. They still seem to be evaluated since I can see some form of response `number/50` but nothing is shown...

![image](https://user-images.githubusercontent.com/33512740/114761516-dd4a7e00-9d60-11eb-8d23-9001d4396568.png)

Maybe you could double check if this is also the case for you with the newest master from `telescope.nvim`, else it might just be me.

2021-04-20 20:25 UTC, luc-tielen commented
Like I mentioned in #2, https://github.com/nvim-telescope/telescope.nvim/commit/d27907b0dac658dfa2fb7e63103675d1832f33e0 may be the cause for the sorter issues. You can try updating telescope again?

Also sorry I'm taking so long to respond. I finally have some more free time again :-)

2021-04-21 05:33 UTC, ndzik commented
Updating Telescope fixes the issue with the sorter being `nil`, but the overall problem of no entries appearing persists.

I do not really understand the flow of Telescope and how the final results are really send and displayed in the `Result` buffer. At least I know I am not the only one with the issue.

I will debug this a bit more as soon as I can free up some time again. (:

2022-06-09 12:51 UTC, ndzik commented
I am completely out of the loop here after last year and also I am cleaning up open PRs.
I will close this in the meantime to not pollute your repo (:
Sorry that I was not able to find time to fix this. I still appreciate every second you spent! :pray:

2022-06-09 12:51 UTC, closed without merging